name: Déploiement Pro

on:
  push:
    branches:
      - main

jobs:
  deploy-dev:
    runs-on: self-hosted

    steps:
      - name: 🔄 Récupération du code
        uses: actions/checkout@v4

      - name: 🚀 Déploiement sur minesweeper-pro
        run: |
          cd minesweeper-ui
          export CONFIG_ENV=pro
          echo "📦 Installation des dépendances..."
          npm install

          echo "🏗️  Build du site..."
          npm run build

          echo "🔍 Vérification du dossier dist/"
          if [ ! -d "dist" ]; then
            echo "❌ Le dossier 'dist/' n'a pas été généré. Abandon."
            exit 1
          fi

          echo "🧹 Nettoyage du dossier de test..."
          rm -rf /opt/minesweeper/minesweeper-pro/*

          echo "📁 Copie des fichiers dans minesweeper-pro..."
          cp -r dist/* /opt/minesweeper/minesweeper-pro/

          echo "✅ Déploiement du front PRO terminé !"

          cd ../minesweeper-api
          echo "📦 Installation des dépendances..."
          mvn clean package

          echo "🔍 Vérification du dossier target/"
          if [ ! -d "target" ]; then
            echo "❌ Le dossier 'target/' n'a pas été généré. Abandon."
            exit 1
          fi

          echo "🧹 Nettoyage du dossier de test..."
          rm -rf /opt/minesweeper/minesweeper-api-pro/minesweeper-api-runner.jar

          echo "📁 Copie des fichiers dans minesweeper-api-pro..."
          cp -r target/minesweeper-api-1.0.0-SNAPSHOT-runner.jar /opt/minesweeper/minesweeper-api-pro/minesweeper-api-runner.jar
          sudo chown minesweeper-api-pro: /opt/minesweeper/minesweeper-api-rec/minesweeper-api-runner.jar

          echo "📁 redemarrage du service..."
          sudo systemctl restart quarkus-minesweeper-api-pro.service

          echo "✅ Déploiement PRO terminé !"
